zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8081

server:
  port: 6000

ribbon:
  eureka:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/